version: "3.8"
services:
  mongo:
    image: mongo
    container_name: boilerplate-mongo
    networks:
      - boilerplate-network-private
    volumes:
      - mongodb:/data/db

  api:
    container_name: boilerplate-api
    networks:
      - boilerplate-network-private
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongodb:

networks:
  boilerplate-network-private:
    driver: bridge
