version: "3.8"

services:
  mongo:
    image: mongo
    container_name: boilerplate-mongo
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: boilerplate-api
    build: 
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongodb:
